# Site Settings
title: یه بشقاب
tagline: پیشنهاد غیرمنتظره و شگفت‌انگیز

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
timezone: Asia/Tehran
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
